### ISSUE TITLE
Release 1.4.5 has BC breaks

### ISSUE THREAD

**Issue by devantoine** [coopTilleuls/CoopTilleulsForgotPasswordBundle#109]
Hello,

This commit: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/pull/106/commits/af606481982b1bec00fa4d8308d0e772203f13fa introduces a BC break by removing `CREATE_TOKEN` and `UPDATE_PASSWORD` from the `ForgotPasswordEvent` class.

I wasn't expecting seeing my code broke after upgrading a PATCH version.

**Comment by vincentchalamon** [comment]
Hi @devantoine,

Sorry for this bug. I'm gonna fix it in a new PATCH version asap.

**Comment by vincentchalamon** [comment]
v1.4.6 has just been published and should fix it

**Comment by devantoine** [comment]
Thank you 🙏
