### ISSUE TITLE
Minutes of expiry date fixed to numeric representation of the current month

### ISSUE THREAD

**Issue by bmomut** [coopTilleuls/CoopTilleulsForgotPasswordBundle#132]
**Describe the bug**

Wrong format in ForgotPasswordManager.php:73 causing minutes value of expiring date to be fixed to the numeric representation of the current month.

![image](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/assets/82022891/525dcdf1-aaf3-4393-b811-c85e75b00a3f)

According to [PHP Docs](https://www.php.net/manual/en/datetime.format.php) the "m" format in this line stands for "Numeric representation of a month, with leading zeros" and should have been "i" instead which stands for "Minutes with leading zeros".

**To Reproduce**

1. Request a token.

**Expected behavior**

Creation of a new token that expires at current date + duration set in the package's config. 

**Screenshots**

"expiredAt" before format -> "expiredAt" after format (expires_in is set to "1500 seconds" ).
![image](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/assets/82022891/6420ee4e-c04a-4e40-9c25-8e2d32a3f4bb)

**Desktop (please complete the following information):**

- OS: Debian 12
- Browser: Firefox
- Version: 115.5.0esr

**Comment by vincentchalamon** [comment]
Nice catch, thanks for the report @bmomut!
It has been fixed and released as v1.5.2
