### ISSUE TITLE
Error using fosrestbundle and jms serializer

### ISSUE THREAD

**Issue by pasblin** [coopTilleuls/CoopTilleulsForgotPasswordBundle#24]
Hi , 
I'm using your bundle together with fosrestbundle and jms Serializer, but im getting this error:

Type error: Argument 2 passed to CoopTilleuls\ForgotPasswordBundle\Controller\ForgotPasswordController::__construct() must be an instance of Symfony\Component\Serializer\Normalizer\NormalizerInterface, instance of JMS\Serializer\Serializer given

Another question is.. how can i customize de exceptions text of your bundle?

Regards

**Comment by vincentchalamon** [comment]
Hello @pasblin,

Thanks for your feedback. Currently, this bundle only supports [Symfony Serializer](http://symfony.com/doc/current/components/serializer.html). But feel free to contribute by adding a bridge for both Symfony & JMS serializers for better compatibility 😃 I would be happy to help you on this feature.

To customize exceptions texts, it's currently not possible to translate/customize them as it will add a dependency on translator, which is IMO not so useful in this bundle. In which case do you need to customize exceptions texts?

**Comment by pasblin** [comment]
Hello, about the translations, it was only to be able to translate them into spanish, but it is not important.
Thx and regards.

**Comment by pasblin** [comment]
Hello!
When do you think that the implementation with fostrestbundle will be finished? 
Thx and regards.

**Comment by vincentchalamon** [comment]
@pasblin Thanks for your feedback, the PR has been merged & released.
