### ISSUE TITLE
serializer error

### ISSUE THREAD

**Issue by pasblin** [coopTilleuls/CoopTilleulsForgotPasswordBundle#26]
Hi,
Im again , using de new release im getting this error now:
`PHP Fatal error:  Uncaught Symfony\Component\Dep
endencyInjection\Exception\ServiceNotFoundException: The service "coop_tilleuls_forgot_password.controller.forgot_  
                                                                                                                      password" has a dependency on a non-existent serv
ice "serializer". in /var/www/api/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Check`
I think the problem is here `new Definition($class, [new Reference('serializer')]))->setPublic(false);`

Mi config file:
`coop_tilleuls_forgot_password:`
    `password_token_class: 'AppBundle\Entity\PasswordToken'`
    `user_class:           'AppBundle\Entity\User'`
    `use_jms_serializer: true`

 
Regards!

**Comment by pasblin** [comment]
In mi config.yml the serializer is commented:
`#serializer:      { enable_annotations: true }`

**Comment by vincentchalamon** [comment]
Hello @pasblin,
My bad, I though the JMSSerializer could map a service `serializer` with the same id. I'll create a hotfix to fix it. Thanks for your report.
You may have to update your configuration to adapt to it.

**Comment by pasblin** [comment]
No problem, i will update when the hotfix will be finish.
Regards!

**Comment by pasblin** [comment]
Hi! i see that the pull request is finished,  can yoy merge it ?
Thx

**Comment by vincentchalamon** [comment]
@pasblin It's merged & tagged: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/releases/tag/v1.0.6

**Comment by vincentchalamon** [comment]
@pasblin Can you confirm me it's working in your projet this time ? 😃

**Comment by pasblin** [comment]
Hi , the bundle works now! :) , thx and regards
