### ISSUE TITLE
lock token generation for user on too many attempt

### ISSUE THREAD

**Issue by gorghoa** [coopTilleuls/CoopTilleulsForgotPasswordBundle#39]
If too many reset password requests are done in a short delay, we may want to add a mechanism to calm down the attacker.

First discussed here: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/issues/37#issuecomment-371454198

Plus, in regard of #38, the response to the attacker should be the same whether the email exists or not. Hence we cannot protect by verifying a request counter on a token entity. The check can then only be made by data in the Request… soooo, maybe out of this bundle scope (hard to say)?

Note: This could be done by server configuration (fail2ban, etc).

**Comment by vincentchalamon** [comment]
Closing as this can be solved by a server configuration (fail2ban, etc.) or a Symfony Bundle: [anyx/login-gate-bundle](https://packagist.org/packages/anyx/login-gate-bundle)
