### ISSUE TITLE
Support multiple users

### ISSUE THREAD

**Issue by vincentchalamon** [coopTilleuls/CoopTilleulsForgotPasswordBundle#40]
Currently, this bundle only support a single user. But in some projects, we may handle multiple users.
It should be possible in this bundle to support multiple users classes

**Comment by crashbtz** [comment]
Hello,
Any update about this feature? Or maybe a workaround?

Thanks

**Comment by vincentchalamon** [comment]
Hello @crashbtz,

Sadly, this feature hasn't evolved. It's a big feature which may require a refacto of some core elements of the bundle.
No workaround have been found for it yet.
If you have some time to work on this feature, feel free to open a PR, I'll be happy to contribute.

Regards

**Comment by aziz-harazi** [comment]
Hello @vincentchalamon , We currently use CoopTilleulsForgotPassword and we also need to use it for many providers. Are you working on it ? or have you any tracks ?

We will probably open a PR

Thank you

**Comment by vincentchalamon** [comment]
Hello @aziz-harazi,

I didn't find enough time to work on this one. I will highly appreciate if you could open a PR to work on it :-)

Regards
Vincent
