### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by imaximius** [coopTilleuls/CoopTilleulsForgotPasswordBundle#54]
Could you please increase version of bundle requirements to version ^5.0?

**Comment by vincentchalamon** [comment]
Hi @imaximius,

Before I merge my PR, could you give a try to the `symfony-5` branch on your project and give me your feedback in case of any issue, please?

```
composer require tilleuls/forgot-password-bundle:dev-symfony-5
```

I did my best to handle all deprecations to ensure Symfony 3.4 / 4.* / 5.* compatibility. Be sure to read [the documentation on `symfony-5` branch](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/symfony-5/Resources/doc/getting_started.md), especially about the EventSubscribers.

**Comment by imaximius** [comment]
Hi @vincentchalamon 
Sorry for the late answer. I've forked your project and get done this issue on my own. I've created a pull-request with my changes https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/pull/56 so if you want you can take a look on it and maybe use something.

BTW thanks for the component!

**Comment by vincentchalamon** [comment]
Hi @imaximius,

Sadly, your PR contains some BC breaks et security failures. I'm gonna reeview it, so you'll see about what to care about in your future PRs :-) But I'm not sure to keep it then as another PR about Symfony 5 compatibility has already been started earlier: https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/pull/55

Could you test my `symfony-5` branch locally, please, and give me your feedbacks?

```
composer require tilleuls/forgot-password-bundle:dev-symfony-5
```

Thanks

Vincent

**Comment by imaximius** [comment]
Sorry, just mentioned that some unit tests are broken. This is quick fix, so it seems this PR need to be updated.

Sure, I'll test your branch and give you a feedback

**Comment by vincentchalamon** [comment]
@imaximius v1.3.0 has been tagged, supporting Symfony 5.0
