### ISSUE TITLE
Issue with intergrating 

### ISSUE THREAD

**Issue by movingarrow** [coopTilleuls/CoopTilleulsForgotPasswordBundle#58]
I have symfony 4.4.2 and was trying to integrate CoopTilleulsForgotPasswordBundle. But I have issue on a last step when I suppose to receive POSt request with the new password and the token. Here is what I got:
 Could not resolve argument $password of "coop_tilleuls_forgot_password.controller.update_password()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?

But when I try to register it as service it gives me error:
Controller "CoopTilleuls\ForgotPasswordBundle\Controller\UpdatePassword" requires that you provide a value for the "$password" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

So what I'm missing here? Thank you

**Comment by movingarrow** [comment]
here is my service.yaml

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    mailer_email_from: '%env(MAILER_EMAIL_FROM)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    App\Controller\ResetPasswordController:
#        tags: ['controller.service_arguments']
#        arguments:
#            $forgotPasswordManager: '@coop_tilleuls_forgot_password.manager.forgot_password'
    CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager:
        class: CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager
        arguments:
            $passwordTokenManager: '@coop_tilleuls_forgot_password.manager.password_token'
            $manager: '@coop_tilleuls_forgot_password.manager.doctrine'
            $userClass: App\Entity\Tuser

#    CoopTilleuls\ForgotPasswordBundle\Controller\UpdatePassword:
#        class: CoopTilleuls\ForgotPasswordBundle\Controller\UpdatePassword
#        tags: ['controller.service_arguments']

    coop_tilleuls_forgot_password.controller.update_password:
        class: CoopTilleuls\ForgotPasswordBundle\Controller\UpdatePassword
        tags: ['controller.service_arguments']

**Comment by vincentchalamon** [comment]
Hi @movingarrow,

Why do you need to override the controller? I don't anywhere [in the doc](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/tree/master/Resources/doc) this part. :thinking:

**Comment by movingarrow** [comment]
Thank you for your response! I really appreciate it. Well first, i tried to
customize response with some custom json in ResetPassword controller by
overriding it. And it worked. But this is definitely not the crucial part
and I can remove it.
So I guess what you are saying is if I remove my overriding of
ResetPassword controller it will all work like a charm?

**Comment by vincentchalamon** [comment]
If you follow the documentation, it will work like a charm, the tests written in this bundle are validating this process :smiley:

If you want to change the response of the UpdatePasswordController, I advise you to listen to the `kernel.response` event, restrict it to the `coop_tilleuls_forgot_password.update` route and change the response directly from the $event object: https://symfony.com/doc/current/reference/events.html#kernel-response

**Comment by movingarrow** [comment]
Thank you! I'll try again from a scratch later today and will let you know
how it goes!

**Comment by vincentchalamon** [comment]
Great, let me know if you have any troubles about it.

**Comment by movingarrow** [comment]
Hi. I tried again and still got stuck with the same error. Well it turned
out that if I custom change password_field in config with anything but
'password' value it will give error.

coop_tilleuls_forgot_password:
    password_token:
        class: App\Entity\PasswordToken # required
        expires_in: 1 day
        user_field: user
        serialization_groups: []
    user:
        class: App\Entity\Tuser # required
        email_field: usrMail
        password_field: usrPwd

**Comment by vincentchalamon** [comment]
The `password_field` is the name of the password field in the `POST /forgot_password/[token}` route, in your example:
```json
{
    "usrPwd": "foo"
}
```

**Comment by movingarrow** [comment]
Yes, I tried it this way but it doesn't work. Only when I change it back to
"password" : "too" it works flawlessly.
