### ISSUE TITLE
SwaggerDecorators in api-platform 2.6.1 changed, so the bundle's endpoint decorator will fail

### ISSUE THREAD

**Issue by Jurek-Raben** [coopTilleuls/CoopTilleulsForgotPasswordBundle#69]
**Describe the bug**
This nice bundle can provide a swagger decorator e.g. under the swagger ui url /api. Since the way a decorator is setup changed a lot in api-platform 2.6.1 (vs. 2.5.9), the decorator will fail now.

Old way: https://web.archive.org/web/20201024152406/https://api-platform.com/docs/core/jwt/
New way: https://api-platform.com/docs/core/jwt/

**To Reproduce**
Simply composer update a symfony 5.2.1 / api-platform 2.5.9 (or lower) project to recent versions.

**Expected behavior**
The endpoint decorator of this bundle should be still listed in the swagger ui.

**Comment by vincentchalamon** [comment]
@Jurek-Raben it has been fixed, but not released yet. If you want to try the feature, you can use the `dev-main` version of this bundle (/!\ it's a development version, but no BC break should appear)

**Comment by Jurek-Raben** [comment]
I think this also was bugfixed in API platform, since the incompatibility was actually a bug.

**Comment by vincentchalamon** [comment]
I'll tag it in 1.3.5 soon. Don't hesitate to try it on your own and give me your feedback!
