### ISSUE TITLE
possibility of not using a database

### ISSUE THREAD

**Issue by pasblin** [coopTilleuls/CoopTilleulsForgotPasswordBundle#70]
**Is your feature request related to a problem? Please describe.**
I think it would be fine implement the possibility of validating an account only validating the token without using a database, something similar to the LexikJWTAuthenticationBundle. 
With this we would avoid unconfirmed tokens in the database for example.

**Describe the solution you'd like**
Create a token with the expiration date fields for example and validate that the token is valid and does not contain an expired expiration date.
**Describe alternatives you've considered**

**Additional context**

Thx and regards.

**Comment by vincentchalamon** [comment]
Hi @pasblin,

If I understood your ticket correctly, your idea to "_validate_" a token without a database would be to check if a token is valid without using any database, right? If so, it can easily be done [using a custom manager](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/blob/main/Resources/doc/use_custom_manager.md).

Let me know if it solves your issue.
