### ISSUE TITLE
Encode password

### ISSUE THREAD

**Issue by Boudj31** [coopTilleuls/CoopTilleulsForgotPasswordBundle#86]
Hello , 

I Noticed everything is ok but when i submit my new password, in database it's not encoded,
How can i encode it in UpdatePassword methods ?

Thanks

**Comment by vincentchalamon** [comment]
Hi @Boudj31,

The password encoding process is not part of this bundle. You should follow this Symfony documentation: https://symfony.com/blog/new-in-symfony-5-3-passwordhasher-component
