### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by matmkian** [coopTilleuls/CoopTilleulsForgotPasswordBundle#92]
I've just upgraded from Symfony 5 to Symfony 6 and I can see 2 deprecation warnings in the logs:

`Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "App\EventSubscriber\ForgotPasswordEventSubscriber" now to avoid errors or add an explicit @return annotation to suppress this message.`

`Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "CoopTilleuls\ForgotPasswordBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by vincentchalamon** [comment]
Hi @matmkian,

Thanks for the update. Any PR will be more than welcome :-)

**Comment by vincentchalamon** [comment]
Hi @matmkian,

It looks like the first deprecation is in your project (`App\EventSubscriber\ForgotPasswordEventSubscriber`). I've published a fix on the `main` branch for the second deprecation.
